---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: charre-server 
  namespace: losstracker
spec:
  selector:
    matchLabels:
      app: charre-server 
  replicas: 1
  template:
    metadata:
      labels:
        app: charre-server 
    spec:
      containers:
        - name: charre-server
          image: ghcr.io/symlons/charre/feedback:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: MONGO_HOST
              value: 192.168.123.192
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              value: ""
            - name: MONGO_PASSWORD
              value: ""
            - name: MONGO_DB
              value: test
          livenessProbe:
            httpGet:
              path: feedback/liveness
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: feedback/readiness
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      # imagePullSecrets:
      #   - name: gitlabregcred
---
apiVersion: v1
kind: Service
metadata:
  name: charre-server
  namespace: losstracker
spec:
  selector:
    app: charre-server 
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
# Middleware to rewrite /api paths
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: charreapi
  namespace: losstracker
spec:
  replacePathRegex:
    regex: "^/charre/(.*)"
    replacement: "/$1"
---
# Ingress for the Client  /charre
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: charre-ingress
  namespace: losstracker
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: mlstatstracker.org
      http:
        paths:
          - path: /charre
            pathType: Prefix
            backend:
              service:
                name: charre-server 
                port:
                  number: 5000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: losstracker-api
  namespace: losstracker
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`mlstatstracker.org`) && PathPrefix(`/charre`)
      kind: Rule
      services:
        - name: charre-server 
          port: 5000
      middlewares:
        - name: charreapi # Reference to the middleware
