kind: Deployment
apiVersion: apps/v1
metadata:
  name: app
  namespace: losstracker

  labels:
    component: app
    app: charre
spec:
  replicas: 1
  selector:
    matchLabels:
      component: app
      app: charre
  template:
    metadata:
      labels:
        component: app
        app: charre
    spec:
      containers:
        - name: app
          image: ghcr.io/symlons/charre/app:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 8501
              protocol: TCP
          env:
            - name: FEEDBACK_URL
              value: "http://mlstatstracker.org/charre/feedback"
            - name: CLASSIFIER_URL
              value: "https://fabio-kost--flask-server-flask-app.modal.run/model_endpoint"
          livenessProbe:
            httpGet: 
              path: /healtz
              port: 8501
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
---
kind: Service
apiVersion: v1
metadata:
  name: app
  namespace: losstracker
  labels:
    component: app
    app: charre
spec:
  ports:
    - name: http
      port: 8501
      targetPort: 8501
  selector:
    component: app
    app: charre
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: charre-server 
  namespace: losstracker
spec:
  selector:
    matchLabels:
      app: charre-server 
  replicas: 1
  template:
    metadata:
      labels:
        app: charre-server 
    spec:
      containers:
        - name: charre-server
          image: ghcr.io/symlons/charre/feedback:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: MONGO_HOST
              value: 192.168.123.192
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              value: ""
            - name: MONGO_PASSWORD
              value: ""
            - name: MONGO_DB
              value: charre
          livenessProbe:
            httpGet:
              path: feedback/liveness
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: feedback/readiness
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: charre-server
  namespace: losstracker
spec:
  selector:
    app: charre-server 
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP

---
# 1) Middleware to strip "/app" or "/charre"
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-charre
  namespace: losstracker
spec:
  stripPrefix:
    prefixes:
      - /charre

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-app
  namespace: losstracker
spec:
  stripPrefix:
    prefixes:
      - /app

---
# 2) Single IngressRoute that handles both routes
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: losstracker-apps
  namespace: losstracker
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`mlstatstracker.org`) && PathPrefix(`/charre`)
      kind: Rule
      middlewares:
        - name: strip-charre
      services:
        - name: charre-server
          port: 5000

    - match: Host(`mlstatstracker.org`) && PathPrefix(`/app`)
      kind: Rule
      services:
        - name: app
          port: 8501
