kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: charre
  namespace: charre
#  annotations:
#    ingress.kubernetes.io/ssl-redirect: "true"
#    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: traefik
#  tls:
#    - hosts:
#        - charre.trunijoh.ccp2.ch
#      secretName: charre-tls-cert
  rules:
    - host: charre.trunijoh.ccp2.ch
      http:
        paths:
          - path: /feedback
            pathType: Prefix
            backend:
              service:
                name: feedback
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 8501
