name: ci

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  APP_IMAGE_NAME: ${{ github.repository }}/app
  APP_IMAGE_TAG: latest
  FEEDBACK_IMAGE_NAME: ${{ github.repository }}/feedback
  FEEDBACK_IMAGE_TAG: latest

jobs:
  publish-containers:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Authenticate to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        id: push-app
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}:${{ env.APP_IMAGE_TAG }}
      - name: Build and push image
        id: push-feedback
        uses: docker/build-push-action@v6
        with:
          context: ./feedback
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.FEEDBACK_IMAGE_NAME }}:${{ env.FEEDBACK_IMAGE_TAG }}
